#!/bin/sh

# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
     [ ! -f "$i" ] && continue

     case "$i" in
	*.sh)
	    # Source shell script for speed.
	    (
		trap - INT QUIT TSTP
		set start
		. $i
	    )
	    ;;
	*)
	    # No sh extension, so fork subprocess.
	    $i start
	    ;;
    esac
done

# echo 1 > /dev/jp_hgd_gpio_ctl_enable_refrigerator

# export TZ=UTF-8
# export XDG_RUNTIME_DIR=${XDG_RUNTIME_DIR:-/var/run}
# export LD_LIBRARY_PATH=/root/app/ui/test_lib

# /root/app/ui/jpGasDetection &
# sleep 5
# /root/app/ui/HGD &